name: food_app
description: "Flutter App สำหรับแสดงอาหาร สูตร และแผนที่ร้าน"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  url_launcher: ^6.2.6
  geolocator: ^14.0.2
  youtube_player_flutter: ^9.1.3
  flutter_map: 5.0.0
  latlong2: ^0.9.0
  intl: ^0.18.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/food.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/new_icon.png"
